FROM ultralytics/ultralytics:latest
RUN apt-get install \
  'ffmpeg'\
  'libsm6'\
  'libxext6'  -y
COPY requirements.txt requirements.txt
COPY setup.py setup.py
RUN pip install -e .
RUN pip install -r requirements.txt
COPY waste waste/

CMD uvicorn waste.api.fast:app --host 0.0.0.0 --port $PORT
