FROM python:3.10-buster
RUN apt-get update
RUN apt-get install \
  'ffmpeg'\
  'libsm6'\
  'libxext6'  -y
RUN pip install --upgrade pip
COPY Makefile Makefile
COPY setup.py setup.py
COPY requirements.txt requirements.txt
COPY waste waste/
RUN make install
CMD python waste/interface/main.py
